# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_List' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo_List

    pod 'Alamofire'
    #pod 'SVProgressHUD', '~> 2.2.6'
    pod 'MBProgressHUD'
end
